services:

  pgsql:
    container_name: parsegraph_os_database_container
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-p4ssw0rd} # environment variable that sets the superuser password for PostgreSQL
      POSTGRES_USER: ${DB_USER:-user} # variable that will create the specified user
      POSTGRES_DB: ${DB_NAME:-user} # the name of your db
    ports:
      - 5432:5432

  pg_api_opensource:
    container_name: parsegraph-api_os
    # we are not going to use the Python image as is but rather tweak one to our needs
    build:
      context: parsegraph-back-atlantis
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    # the Flask app' code will go into the `app` folder of your project and be mapped to `/usr/src/app` in the container
    volumes:
      - ./parsegraph-front-atlantis/public/envconfig.json:/usr/src/app/envconfig.json
      - ./parsegraph-front-atlantis/public/data:/usr/src/app/data

  nginx_opensource:
    container_name: evaxplainify_viz_os
    build:
      context: parsegraph-front-atlantis
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "12443:443"
    volumes:
      - ./parsegraph-front-atlantis/public/envconfig.json:/var/www/html/envconfig.json
